name: python pipeline

on: push

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - run: python hello.py
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Upload Artifact 
      uses: actions/upload-artifact@v4
      with:
        name: hello
        path: .
    - name: Cacheing
      uses: actions/cache@v2
      with:
        key: 'the-cache-key'
        path: .
    
    
  
